### ISSUE TITLE
这两个文件，一比较，思源就会重启

### ISSUE THREAD

**Issue by wish5115** [etchnight/siyuan-plugin-diff#4]
动画演示如下

![t3](https://github.com/user-attachments/assets/581b3b4e-ecf9-4d49-9a5c-34a65f973c62)

测试文件如下

[demo.sy.zip](https://github.com/user-attachments/files/16400449/demo.sy.zip)

正常文本文件比较没问题。

**Comment by etchnight** [comment]
比较挂件块引起的，已设置为不输出挂件内容
